Resources: 
  TestInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-08f32efd140b7d89f
      InstanceType: t2.micro        
      Tags:
      - Key: Name
        Value: VPCAPublicEC2            
      SubnetId: subnet-0303931f153f6ed16
      SecurityGroupIds:
       - !GetAtt EC2SecurityGroup.GroupId

  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: EC2 VPCA Public Subnet
      GroupName: EC2SecurityGroupVPCA
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0       
  

  