AWSTemplateFormatVersion: "2010-09-09"
Description: Create NAT Gateway in Public Subnet
Parameters:
  ExportVPCA:
    Description : Name of the First VPC
    Type: String
  ExportVPCB:
    Description : Name of the Second VPC
    Type: String

Resources:
  ElasticIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: VPC
      Tags: 
        - Key: Name
          Value: EIPTest

  NATGatewayPublic:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt ElasticIP.AllocationId      
      SubnetId:
        Fn::ImportValue: !sub ${ExportVPCA}-PublicSubnetID
      Tags: 
        - Key: Name
          Value: NATGW

  PrivateRoute:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0 
      NatGatewayId: !Ref NATGatewayPublic
      RouteTableId: !sub ${ExportVPCB}-PrivateRouteTable


