---
# Base template for S3
Resources:
  ATUClds3:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: "PublicRead"
      BucketName: "CldDemoS3"
 #bucketnames are lowercase
      Tags:
      - Key: "cldS3Demo"
        Value: "CldS3"
Outputs:
  # Export S3
  OutTestS3:
    Description: S3 Bucket  
    Value: !Ref TestS3Bucket
    Export:
      Name: TestS3Bucket
